services:
  web:
    build:
      context: .
      dockerfile: src/docker/Dockerfile.development
    command: ["bash", "./src/config/bootstrap.sh"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./.env

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
