FROM python:3.12 AS build

WORKDIR /app

COPY requirements.in .
RUN pip install --no-cache-dir pip-tools && \
    pip-compile requirements.in --generate-hashes -o requirements.txt && \
    pip install --no-cache-dir -r requirements.txt

FROM python:3.12
WORKDIR /app
COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY . .
